-- Lab3-查询执行 测试点7：归并连接
set enable_sortmerge = true;
create table student (id int, name char(8), class int);
create table grade (sid int, course char(8), score float);
create table course (name char(8), credit int);
create table bonus (score float, extra int);
create table empty_t (id int);
insert into student values (3, 'Carol', 2);
insert into student values (1, 'Alice', 1);
insert into student values (4, 'Dave', 2);
insert into student values (2, 'Bob', 1);
insert into student values (5, 'Erin', 3);
insert into grade values (2, 'DB', 88.0);
insert into grade values (1, 'OS', 92.5);
insert into grade values (3, 'DB', 75.0);
insert into grade values (1, 'DB', 60.0);
insert into grade values (2, 'OS', 70.5);
insert into grade values (6, 'AI', 99.0);
insert into grade values (1, 'AI', 81.0);
insert into grade values (3, 'OS', 66.0);
insert into course values ('OS', 4);
insert into course values ('DB', 3);
insert into course values ('AI', 2);
insert into course values ('ML', 2);
insert into course values ('DB', 5);
insert into bonus values (88.0, 1);
insert into bonus values (70.5, 2);
insert into bonus values (70.5, 3);
insert into bonus values (99.0, 4);
insert into bonus values (50.0, 5);
select * from student, grade where student.id = grade.sid;
select student.name, grade.course, grade.score from grade, student where grade.sid = student.id and grade.score > 70.0;
select * from student, grade where student.class = grade.sid;
select * from grade join course where grade.course = course.name;
select student.name, course.name, course.credit from student, grade, course where student.id = grade.sid and grade.course = course.name;
select * from grade, bonus where grade.score = bonus.score;
select * from student, grade where student.id = grade.sid and student.class < grade.sid;
select * from student, grade where student.id = grade.sid and student.class <> 1;
select * from student, course where student.name = course.name;
select * from student, empty_t where student.id = empty_t.id;
select student.id, grade.sid from student, grade where student.id > grade.sid and grade.course = 'AI';
set enable_sortmerge = false;
select * from student, grade where student.id = grade.sid;
set enable_hashjoin = true;
