-- Lab3-查询执行 测试点6：唯一索引
-- 注意：本测试不在建了索引的列上写等值条件，因此不会用到索引扫描算子。
create table stu (id int, name char(8), score float);
create unique index stu(id);
insert into stu values (1, 'Alice', 90.0);
insert into stu values (2, 'Bob', 80.5);
insert into stu values (1, 'Carol', 70.0);
select * from stu;
update stu set id = 2 where name = 'Alice';
select * from stu;
update stu set id = 1 where name = 'Alice';
update stu set id = 3 where name = 'Alice';
insert into stu values (1, 'Carol', 70.0);
select * from stu;
delete from stu where name = 'Bob';
insert into stu values (2, 'Dave', 60.0);
select * from stu;
create table course (cid int, sid int, tag char(4));
insert into course values (1, 10, 'a');
insert into course values (2, 10, 'b');
create unique index course(sid);
create index course(sid);
insert into course values (3, 10, 'c');
create unique index course(cid, sid);
insert into course values (1, 10, 'd');
insert into course values (1, 11, 'e');
select * from course;
drop index course(sid);
create unique index course(sid);
drop index course(cid, sid);
insert into course values (1, 10, 'f');
select * from course;
create table pair (a int, b int, c char(4));
create unique index pair(a);
create unique index pair(b);
insert into pair values (1, 1, 'x');
insert into pair values (2, 1, 'y');
insert into pair values (2, 5, 'y');
insert into pair values (3, 6, 'z');
select * from pair;
update pair set a = 7, b = 1 where c = 'y';
select * from pair;
insert into pair values (7, 20, 'w');
insert into pair values (2, 21, 'w');
insert into pair values (22, 5, 'w');
select * from pair;
